name: Evofly
version: 1.0.0+1
publish_to: none
description: evofly app for gemastik 2023.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^4.6.3
  shared_preferences: ^2.1.2
  awesome_bottom_bar: ^1.2.2
  cloud_firestore: ^4.8.1
  youtube_player_flutter: ^8.1.2
  shimmer: ^3.0.0
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true

